title: zzz
frequency: 5
dirfilter:
- node_modules
- .git
- dist
ext:
- ts
- js
enablerun: false
action:
  before:
  - echo "npm install"
  after:
  - "npm run dev"
link: https://github.com/midoks/zzz
